"""Generate start.bat with proper GBK encoding."""
import os

lines = []

def add(line):
    lines.append(line)

add('@echo off')
add('setlocal enabledelayedexpansion')
add(r'set ROOT=%~dp0')
add('title 电商RAG知识库问答系统 - 一键启动')
add('')
add('echo.')
add('echo   ============================================================')
add('echo        电商 RAG 知识库问答系统 - 一键启动')
add('echo   ============================================================')
add('echo.')
add('echo   [1/4] 检查运行环境...')
add('echo.')
add("for /f \"tokens=*\" %%i in ('python --version 2^>^&1') do set PYVER=%%i")
add('if "%PYVER%"=="" (')
add('    echo   [X] 未找到 Python，请先安装 Python 3.11+')
add('    pause')
add('    exit /b 1')
add(')')
add('echo         Python: %PYVER%')
add('')
add("for /f \"tokens=*\" %%i in ('node --version 2^>^&1') do set NODEVER=%%i")
add('if "%NODEVER%"=="" (')
add('    echo   [X] 未找到 Node.js，请先安装 Node.js 18+')
add('    pause')
add('    exit /b 1')
add(')')
add('echo         Node.js: %NODEVER%')
add('echo.')
add('echo   [2/4] 配置 Python 后端...')
add(r'cd /d "%ROOT%backend"')
add(r'if exist "venv\Lib\site-packages\fastapi" (')
add('    echo         Python 依赖已就绪')
add(') else (')
add('    echo         正在安装 Python 依赖...')
add(r'    venv\Scripts\python.exe -m pip install -r requirements.txt -q')
add('    echo         Python 依赖安装完成')
add(')')
add('echo         启动后端服务 (FastAPI)...')
add(r'start "RAG-Backend" cmd /k "venv\Scripts\python.exe -m uvicorn app.main:app --host 0.0.0.0 --port 8000"')
add('echo         后端已在新窗口中启动')
add('echo.')
add('echo   [3/4] 配置前端...')
add(r'cd /d "%ROOT%frontend"')
add(r'if exist "node_modules\antd" (')
add('    echo         前端依赖已就绪')
add(') else (')
add('    echo         正在安装前端依赖...')
add('    call npm install')
add('    echo         前端依赖安装完成')
add(')')
add('echo         启动前端服务 (Vite)...')
add(r'start "RAG-Frontend" cmd /k "npm run dev"')
add('echo         前端已在新窗口中启动')
add('echo.')
add('echo   [4/4] 启动完成!')
add('echo.')
add('echo   ============================================================')
add('echo.')
add('echo     系统启动中，请等待两个新窗口就绪（约 5-10 秒）')
add('echo.')
add('echo     前端地址:   http://localhost:5173')
add('echo     后端 API:   http://localhost:8000')
add('echo     API 文档:   http://localhost:8000/docs')
add('echo     管理员账号:  admin / 123456')
add('echo.')
add('echo     关闭此窗口不会影响已启动的服务')
add('echo.')
add('echo   ============================================================')
add('echo.')
add('set /p OPEN=是否打开前端页面? (Y/N): ')
add('if /i "%OPEN%"=="Y" start http://localhost:5173')
add('pause')

content = '\r\n'.join(lines) + '\r\n'
out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'start.bat')
with open(out_path, 'w', encoding='gbk') as f:
    f.write(content)
print(f'Written: {out_path}')
